name: Backend CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: '3.10'

jobs:
  lint-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install, Run
        run: |
          pip install pipenv
          pip install flake8
          pipenv install
          pipenv run lint

  test-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install, Run
        run: |
          pip install pipenv
          pipenv install
          pipenv run test
    

  build-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    needs:
      - lint-job
      - test-job

    steps:
      - name: check-out repo
        uses: actions/checkout@v3

      - name: Build
        run: |
          docker build -t backend .
