name: Backend CD
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'starter/backend/**'

env:
  PYTHON_VERSION: '3.10'

jobs:
  lint-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install, Run
        run: |
          pip install pipenv
          pip install flake8
          pipenv install
          pipenv run lint

  test-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install, Run
        run: |
          pip install pipenv
          pipenv install
          pipenv run test
    

  deploy-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    needs:
      - lint-job
      - test-job

    steps:
      - name: check-out repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: us-east-1
  
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        working-directory: starter/backend
        run: |
          docker build -t backend:${GITHUB_SHA} .
          docker tag backend:${GITHUB_SHA} 628647790621.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA}
          docker push 628647790621.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA}

      - name: Deploy image into cluster
        run: |
          cd starter/backend/k8s
          aws eks update-kubeconfig --name cluster --region us-east-1
          kustomize edit set image backend=628647790621.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA}
          kustomize build | kubectl apply -f -

      - name: Print application URLs        
        run: |
          kubectl get svc -A
