name: Frontend CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'

env:
  NODE_VERSION: '18.x'

jobs:
  lint-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: "starter/frontend/package-lock.json"

      - name: Install, Run
        run: |
          npm ci
          npm run lint

  test-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend

    steps:
      - name: check-out repo
        uses: actions/checkout@v3

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: "starter/frontend/package-lock.json"

      - name: Install, Run
        run: |
          npm ci
          npm run test

  build-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    needs:
      - lint-job
      - test-job

    steps:
      - name: check-out repo
        uses: actions/checkout@v3

      - name: Install, Run test
        run: |
          npm ci
          npm run test

      - name: Build
        run: |
          docker build -t frontend .
